CREATE TABLE `USERS` (
	`USER_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '사용자의 고유 식별자',
	`CREDIT_SCORE`	BIGINT	NULL	COMMENT '대출 추천을 위한 신용 점수',
	`INCOME_LEVEL`	VARCHAR(50)	NULL	COMMENT '정부 지원 대출 추천을 위한 소득 정보',
	`FAMILY_TYPE`	VARCHAR(50)	NULL	COMMENT '신혼부부, 청년 등 가구 형태',
	`LAST_LOGIN_AT`	TIMESTAMP	NOT NULL	COMMENT '시스템 사용 이력 관리',
    PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `ACTUAL_TRANSACTION` (
	`TRANSACTION_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '실거래가의 고유 식별자',
	`PROPERTY_ID`	BIGINT	NOT NULL	COMMENT '부동산 물건의 고유 식별자',
	`DEAL_TYPE`	VARCHAR(20)	NULL	COMMENT '매매/전세/월세 (P-001)',
	`DEAL_AMOUNT`	BIGINT	NULL	COMMENT '실제 거래된 금액',
	`DEAL_DATE`	TIMESTAMP	NOT NULL	COMMENT '거래 발생 연월일',
	`DATA_SOURCE`	VARCHAR(50)	NULL	COMMENT '국토부, 서울시 등 데이터 출처 (P-007)',
    PRIMARY KEY (`TRANSACTION_ID`)
);

CREATE TABLE `REAL_ESTATE` (
	`PROPERTY_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '부동산 물건의 고유 식별자',
	`ADDRESS`	VARCHAR(255)	NOT NULL	COMMENT '부동산의 상세 주소',
	`PNU_CODE`	VARCHAR(19)	NULL	COMMENT '필지를 고유하게 식별하는 코드 (P-003)',
	`BUILDING_REG_NUM`	VARCHAR(50)	NULL	COMMENT '건물 관련 정보 조회를 위한 번호 (R-006)',
	`BUILDING_TYPE`	VARCHAR(50)	NULL	COMMENT '아파트, 다세대 등 건물 유형 (P-001)',
	`AREA_SQM`	DECIMAL(10, 2)	NULL	COMMENT '건물 면적 (m²)',
    PRIMARY KEY (`PROPERTY_ID`)
);

CREATE TABLE `MORTGAGE` (
	`MORTGAGE_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '근저당권 정보의 고유 식별자',
	`FILE_ID`	BIGINT	NULL	COMMENT '업로드된 파일 식별자 (R-003)',
	`MAX_CREDIT_AMOUNT`	BIGINT	NOT NULL	COMMENT '근저당권의 채권 최고 금액 (R-005)',
	`CREDITOR`	VARCHAR(100)	NULL	COMMENT '근저당권 설정 기관/개인',
    PRIMARY KEY (`MORTGAGE_ID`)
);

CREATE TABLE `GENERATED_DOCUMENT` (
	`DOCUMENT_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '생성된 계약서/문서의 고유 식별자',
	`PROPERTY_ID`	BIGINT	NOT NULL	COMMENT '부동산 물건의 고유 식별자',
	`USER_ID`	BIGINT	NOT NULL	COMMENT '사용자의 고유 식별자',
	`DOCUMENT_TYPE`	VARCHAR(50)	NOT NULL	COMMENT '매매/전세/월세 계약서 등 (D-001)',
	`CONTRACT_DATA`	JSON	NULL	COMMENT 'JSON 또는 BLOB 형태로 저장된 계약 내용',
	`FINAL_VERSION_ID`	BIGINT	NULL	COMMENT '현재 문서가 가리키는 최신 버전 (FK) - 초기 NULL 허용',
    PRIMARY KEY (`DOCUMENT_ID`)
);

CREATE TABLE `RECOMMENDATION_HISTORY` (
	`RECOMMEND_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '대출 추천 이력 식별자',
	`LOAN_ID`	BIGINT	NULL	COMMENT '대출 상품의 고유 식별자',
	`USER_ID`	BIGINT	NOT NULL	COMMENT '사용자의 고유 식별자',
	`RECOMMENDED_AT`	TIMESTAMP	NOT NULL	COMMENT '추천이 발생한 시점',
	`RECOMMENDATION_TYPE`	VARCHAR(50)	NULL	COMMENT '정부지원/신용점수 기반',
    PRIMARY KEY (`RECOMMEND_ID`)
);

CREATE TABLE `ANALYSIS_TARGET_DOC` (
	`FILE_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '업로드된 파일 식별자 (R-003)',
	`PROPERTY_ID`	BIGINT	NOT NULL	COMMENT '부동산 물건의 고유 식별자',
	`USER_ID`	BIGINT	NOT NULL	COMMENT '사용자의 고유 식별자',
	`DOCUMENT_TYPE`	VARCHAR(50)	NOT NULL	COMMENT '등기부등본, 건축물대장 등',
	`UPLOADED_AT`	TIMESTAMP	NOT NULL	COMMENT '파일 업로드 시점',
	`OCR_EXTRACTED_TEXT`	JSON	NULL	COMMENT 'OCR을 통해 추출된 전체 텍스트 (R-004)',
    PRIMARY KEY (`FILE_ID`)
);

CREATE TABLE `DOCUMENT_VERSION_HISTORY` (
	`VERSION_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '문서 버전의 고유 식별자 (D-003)',
	`DOCUMENT_ID`	BIGINT	NOT NULL	COMMENT '생성된 계약서/문서의 고유 식별자',
	`USER_ID`	BIGINT	NOT NULL	COMMENT '사용자의 고유 식별자',
	`TIMESTAMP`	TIMESTAMP	NOT NULL	COMMENT '버전이 생성된 시점',
	`REQUEST_STATUS`	VARCHAR(20)	NULL	COMMENT '요청/승인/반려 상태 (D-004)',
	`VERSION_DATA`	JSON	NULL	COMMENT '수정된 버전의 실제 데이터나 변경 사항',
    PRIMARY KEY (`VERSION_ID`)
);

CREATE TABLE `RISK_ANALYSIS_RESULT` (
	`RISK_RESULT_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '분석 결과의 고유 식별자 (R-008)',
	`PROPERTY_ID`	BIGINT	NOT NULL	COMMENT '부동산 물건의 고유 식별자',
	`ANALYZED_AT`	TIMESTAMP	NOT NULL	COMMENT '분석이 완료된 시점',
	`TOTAL_SAFETY_SCORE`	DECIMAL(5, 2)	NULL	COMMENT '최종 산출된 종합 안전 점수 (0~100) (R-008)',
	`FINAL_GRADE`	VARCHAR(20)	NULL	COMMENT '안전/주의/위험 등급',
	`REGISTER_RISK_SCORE`	DECIMAL(5, 2)	NULL	COMMENT '등기부등본 기반 위험 점수 (R-005)',
	`JEONSE_RISK_SCORE`	DECIMAL(5, 2)	NULL	COMMENT '전세가율 기반 위험 점수 (R-002)',
	`DISASTER_RISK_GRADE`	VARCHAR(20)	NULL	COMMENT '홍수/재난 위험도 등급 (R-001)',
	`LEGAL_ANALYSIS_RESULT`	JSON	NULL	COMMENT '법률 위반 여부 분석 결과 (L-001)',
    PRIMARY KEY (`RISK_RESULT_ID`)
);

CREATE TABLE `OFFICIAL_LAND_PRICE` (
	`LAND_PRICE_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '공시지가 데이터의 고유 식별자',
	`PROPERTY_ID`	BIGINT	NOT NULL	COMMENT '부동산 물건의 고유 식별자',
	`BASE_YEAR`	INT	NULL	COMMENT '공시지가 산정 기준 연도 (P-003)',
	`OFFICIAL_PRICE`	BIGINT	NULL	COMMENT '고시된 토지 가격',
    PRIMARY KEY (`LAND_PRICE_ID`)
);

CREATE TABLE `LOAN_PRODUCT` (
	`LOAN_ID`	BIGINT	NOT NULL	AUTO_INCREMENT COMMENT '대출 상품의 고유 식별자',
	`PRODUCT_NAME`	VARCHAR(100)	NOT NULL	COMMENT '대출 상품의 이름',
	`BANK_NAME`	VARCHAR(50)	NOT NULL	COMMENT '취급 금융 기관 (C-002)',
	`RATE_MIN`	DECIMAL(5, 3)	NULL	COMMENT '금리 비교를 위한 최저 금리 (C-003)',
	`RATE_MAX`	DECIMAL(5, 3)	NULL	COMMENT '금리 비교를 위한 최고 금리',
	`LIMIT_AMOUNT`	BIGINT	NULL	COMMENT '최대 대출 한도',
	`SUPPORT_TARGET`	VARCHAR(100)	NULL	COMMENT '신혼부부/청년 등 지원 대상 (C-001)',
    PRIMARY KEY (`LOAN_ID`)
);

ALTER TABLE `ACTUAL_TRANSACTION` ADD CONSTRAINT `FK_REAL_ESTATE_TO_ACTUAL_TRANSACTION_1` FOREIGN KEY (
	`PROPERTY_ID`
)
REFERENCES `REAL_ESTATE` (
	`PROPERTY_ID`
);

ALTER TABLE `MORTGAGE` ADD CONSTRAINT `FK_ANALYSIS_TARGET_DOC_TO_MORTGAGE_1` FOREIGN KEY (
	`FILE_ID`
)
REFERENCES `ANALYSIS_TARGET_DOC` (
	`FILE_ID`
);

ALTER TABLE `GENERATED_DOCUMENT` ADD CONSTRAINT `FK_REAL_ESTATE_TO_GENERATED_DOCUMENT_1` FOREIGN KEY (
	`PROPERTY_ID`
)
REFERENCES `REAL_ESTATE` (
	`PROPERTY_ID`
);

ALTER TABLE `GENERATED_DOCUMENT` ADD CONSTRAINT `FK_USERS_TO_GENERATED_DOCUMENT_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `RECOMMENDATION_HISTORY` ADD CONSTRAINT `FK_LOAN_PRODUCT_TO_RECOMMENDATION_HISTORY_1` FOREIGN KEY (
	`LOAN_ID`
)
REFERENCES `LOAN_PRODUCT` (
	`LOAN_ID`
);

ALTER TABLE `RECOMMENDATION_HISTORY` ADD CONSTRAINT `FK_USERS_TO_RECOMMENDATION_HISTORY_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `ANALYSIS_TARGET_DOC` ADD CONSTRAINT `FK_REAL_ESTATE_TO_ANALYSIS_TARGET_DOC_1` FOREIGN KEY (
	`PROPERTY_ID`
)
REFERENCES `REAL_ESTATE` (
	`PROPERTY_ID`
);

ALTER TABLE `ANALYSIS_TARGET_DOC` ADD CONSTRAINT `FK_USERS_TO_ANALYSIS_TARGET_DOC_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `DOCUMENT_VERSION_HISTORY` ADD CONSTRAINT `FK_GENERATED_DOCUMENT_TO_DOCUMENT_VERSION_HISTORY_1` FOREIGN KEY (
	`DOCUMENT_ID`
)
REFERENCES `GENERATED_DOCUMENT` (
	`DOCUMENT_ID`
);

ALTER TABLE `DOCUMENT_VERSION_HISTORY` ADD CONSTRAINT `FK_USERS_TO_DOCUMENT_VERSION_HISTORY_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `RISK_ANALYSIS_RESULT` ADD CONSTRAINT `FK_REAL_ESTATE_TO_RISK_ANALYSIS_RESULT_1` FOREIGN KEY (
	`PROPERTY_ID`
)
REFERENCES `REAL_ESTATE` (
	`PROPERTY_ID`
);

ALTER TABLE `OFFICIAL_LAND_PRICE` ADD CONSTRAINT `FK_REAL_ESTATE_TO_OFFICIAL_LAND_PRICE_1` FOREIGN KEY (
	`PROPERTY_ID`
)
REFERENCES `REAL_ESTATE` (
	`PROPERTY_ID`
);

